[project]
name = "nonebot-plugin-phimg"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "“leonsu-l”", email = "leon_sul@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "PyJWT>=2.8.0",
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.3",
]

[dependency-groups]
dev = [
    "nb-cli>=1.7.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["nonebot_plugin_phimg"]